#!/usr/bin/env bash
#This ensures a placeholder is shipped with CMD build.
for file in src/cld_3/protos/*.proto; do
  echo "#error This is a placeholder file." > ${file%.proto}.pb.cc
done
rm -f src/Makevars configure.log
